---
kind: pipeline
type: docker
name: dockerhub-build-trigger

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: call webhook
  pull: always
  image: curlimages/curl:latest
  environment:
    ENDPOINT:
      from_secret: dockerhub_endpoint
  commands:
  - curl -s -X POST $ENDPOINT
  when:
    branch:
    - master
    event:
    - push
    - cron
    ref:
      exclude:
      - ref/tags/**

---
kind: pipeline
type: docker
name: kaniko-build

platform:
  os: linux
  arch: amd64

depends_on:
- dockerhub-build-trigger

steps:
- name: build
  pull: always
  image: ghcr.io/finitum/drone-kaniko:0.8.2
  settings:
    dockerfile: Dockerfile
    context: .

---
kind: pipeline
type: docker
name: notifications

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: discord
  pull: always
  image: appleboy/drone-discord:1.2.4
  settings:
    message: "{{#success build.status}} ✅ [Build #{{build.number}}]({{build.link}}) of `{{repo.name}}` succeeded.\nevent: **`{{build.event}}`**\ncommit [`${DRONE_COMMIT_SHA:0:7}`](https://git.dotya.ml/${DRONE_REPO}/commit/${DRONE_COMMIT_SHA}) by {{commit.author}} on `{{commit.branch}}`\n```{{commit.message}}``` {{else}} ❌ [Build #{{build.number}}]({{build.link}}) of `{{repo.name}}` failed.\nevent: **`${DRONE_BUILD_EVENT}`**\ncommit [`${DRONE_COMMIT_SHA:0:7}`](https://git.dotya.ml/${DRONE_REPO}/commit/${DRONE_COMMIT_SHA}) by {{commit.author}} on `{{commit.branch}}`\n```{{commit.message}}``` {{/success}}\n"
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token

trigger:
  branch:
  - master
  event:
  - push
  status:
  - success
  - failure

depends_on:
- kaniko-build

---
kind: pipeline
type: docker
name: notifications-cronbuild

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: discord
  pull: always
  image: appleboy/drone-discord:1.2.4
  settings:
    message: "{{#success build.status}} ✅ [Nightly build #{{build.number}}]({{build.link}}) of `{{repo.name}}` succeeded.\nevent: **`{{build.event}}`**\ncommit [`${DRONE_COMMIT_SHA:0:7}`](https://git.dotya.ml/${DRONE_REPO}/commit/${DRONE_COMMIT_SHA}) by {{commit.author}} on `{{commit.branch}}`{{else}} ❌ [Nightly build #{{build.number}}]({{build.link}}) of `{{repo.name}}` failed.\nevent: **`${DRONE_BUILD_EVENT}`**\ncommit [`${DRONE_COMMIT_SHA:0:7}`](https://git.dotya.ml/${DRONE_REPO}/commit/${DRONE_COMMIT_SHA}) by {{commit.author}} on `{{commit.branch}}` {{/success}}"
    webhook_id:
      from_secret: discord_webhook_hourly_id
    webhook_token:
      from_secret: discord_webhook_hourly_token

trigger:
  branch:
  - master
  event:
  - cron
  cron:
  - nightly
  status:
  - success
  - failure

depends_on:
- kaniko-build
